application: t-minuszero
version: 9
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- appstats: on

inbound_services:
- warmup

libraries:
- name: django
  version: 1.4

- name: lxml
  version: latest

- name: PIL
  version: latest


handlers:

- url: /.*
  script: main.application

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
